<?php

namespace ContainerGa1OPWC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DbVppn6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dbVppn6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dbVppn6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ProduceController::addFruit' => ['privates', '.service_locator.SoIa2O7', 'get_ServiceLocator_SoIa2O7Service', true],
            'App\\Controller\\ProduceController::addVegetable' => ['privates', '.service_locator.SoIa2O7', 'get_ServiceLocator_SoIa2O7Service', true],
            'App\\Controller\\ProduceController::processJson' => ['privates', '.service_locator.SoIa2O7', 'get_ServiceLocator_SoIa2O7Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProduceController:addFruit' => ['privates', '.service_locator.SoIa2O7', 'get_ServiceLocator_SoIa2O7Service', true],
            'App\\Controller\\ProduceController:addVegetable' => ['privates', '.service_locator.SoIa2O7', 'get_ServiceLocator_SoIa2O7Service', true],
            'App\\Controller\\ProduceController:processJson' => ['privates', '.service_locator.SoIa2O7', 'get_ServiceLocator_SoIa2O7Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProduceController::addFruit' => '?',
            'App\\Controller\\ProduceController::addVegetable' => '?',
            'App\\Controller\\ProduceController::processJson' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProduceController:addFruit' => '?',
            'App\\Controller\\ProduceController:addVegetable' => '?',
            'App\\Controller\\ProduceController:processJson' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
