<?php

namespace ContainerHr6B7VL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduceServiceFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ProduceServiceFactory' shared autowired service.
     *
     * @return \App\Service\ProduceServiceFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ProduceServiceFactory.php';

        return $container->privates['App\\Service\\ProduceServiceFactory'] = new \App\Service\ProduceServiceFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fruit' => ['privates', 'App\\Repository\\FruitRepository', 'getFruitRepositoryService', true],
            'vegetable' => ['privates', 'App\\Repository\\VegetableRepository', 'getVegetableRepositoryService', true],
        ], [
            'fruit' => '?',
            'vegetable' => '?',
        ]));
    }
}
