<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIu8VDJI\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIu8VDJI/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerIu8VDJI.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerIu8VDJI\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerIu8VDJI\App_KernelTestDebugContainer([
    'container.build_hash' => 'Iu8VDJI',
    'container.build_id' => '5fb95d95',
    'container.build_time' => 1727262486,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIu8VDJI');
