<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEjlK0NO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEjlK0NO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEjlK0NO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEjlK0NO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEjlK0NO\App_KernelDevDebugContainer([
    'container.build_hash' => 'EjlK0NO',
    'container.build_id' => '1880f492',
    'container.build_time' => 1727249481,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEjlK0NO');
