<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_process_json' => [[], ['_controller' => 'App\\Controller\\ProduceController::processJson'], [], [['text', '/api/process']], [], [], []],
    'api_list_fruits' => [[], ['_controller' => 'App\\Controller\\ProduceController::listFruits'], [], [['text', '/api/fruits']], [], [], []],
    'api_list_vegetables' => [[], ['_controller' => 'App\\Controller\\ProduceController::listVegetables'], [], [['text', '/api/vegetables']], [], [], []],
    'api_add_fruit' => [[], ['_controller' => 'App\\Controller\\ProduceController::addFruit'], [], [['text', '/api/fruits']], [], [], []],
    'api_add_vegetable' => [[], ['_controller' => 'App\\Controller\\ProduceController::addVegetable'], [], [['text', '/api/vegetables']], [], [], []],
    'api_remove_fruit' => [['id'], ['_controller' => 'App\\Controller\\ProduceController::removeFruit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/fruits']], [], [], []],
    'api_remove_vegetable' => [['id'], ['_controller' => 'App\\Controller\\ProduceController::removeVegetable'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/vegetables']], [], [], []],
    'App\Controller\ProduceController::processJson' => [[], ['_controller' => 'App\\Controller\\ProduceController::processJson'], [], [['text', '/api/process']], [], [], []],
    'App\Controller\ProduceController::listFruits' => [[], ['_controller' => 'App\\Controller\\ProduceController::listFruits'], [], [['text', '/api/fruits']], [], [], []],
    'App\Controller\ProduceController::listVegetables' => [[], ['_controller' => 'App\\Controller\\ProduceController::listVegetables'], [], [['text', '/api/vegetables']], [], [], []],
    'App\Controller\ProduceController::addFruit' => [[], ['_controller' => 'App\\Controller\\ProduceController::addFruit'], [], [['text', '/api/fruits']], [], [], []],
    'App\Controller\ProduceController::addVegetable' => [[], ['_controller' => 'App\\Controller\\ProduceController::addVegetable'], [], [['text', '/api/vegetables']], [], [], []],
    'App\Controller\ProduceController::removeFruit' => [['id'], ['_controller' => 'App\\Controller\\ProduceController::removeFruit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/fruits']], [], [], []],
    'App\Controller\ProduceController::removeVegetable' => [['id'], ['_controller' => 'App\\Controller\\ProduceController::removeVegetable'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/vegetables']], [], [], []],
];
